eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8762/eureka
      
spring:
  rabbitmq:
    addresses: localhost:5672
    username: guest
    password: guest
    listener:
      simple:
        auto-startup: true
        concurrency: 1
        max-concurrency: 1
        prefetch: 10
        transaction-size: 10
        retry:
          enabled: true
          initial-interval: 20000
          max-attempts: 2
          max-interval: 60000
          multiplier: 2
        default-requeue-rejected: false
