spring:
  rabbitmq:
    addresses: ec2-13-233-62-162.ap-south-1.compute.amazonaws.com:5672
    username: admin
    password: admin
    
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://ec2-13-233-34-229.ap-south-1.compute.amazonaws.com:8762/eureka

http:
 connection:
  timeout: 10000
 read:
  timeout: 10000
  
feign:
 period: 1000
 maxPeriod: 5000
 maxAttempt: 3
 
b2bservice:
 baseUrl: http://ec2-13-233-84-230.ap-south-1.compute.amazonaws.com:8088
 serviceUrl: ${b2bservice.baseUrl}/b2bservice/fetchMtndetails
