spring:
  rabbitmq:
    addresses: localhost:5772
    username: guest
    password: guest
    template:
      retry:
        enabled: true
        initial-interval: 1000
        max-attempts: 5
        max-interval: 5000
        multiplier: 2
    
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8762/eureka

http:
 connection:
  timeout: 10000
 read:
  timeout: 10000
  
feign:
 period: 1000
 maxPeriod: 5000
 maxAttempt: 3
 
b2bservice:
 baseUrl: http://localhost:8088
 serviceUrl: ${baseUrl}/b2bservice/fetchMtndetails
