spring:
  rabbitmq:
    addresses: localhost:5672
    virtual-host: dev-host
rabbitmq:
  micro:
    prop:
      exchange: demo-ex
      routing-key: demo.route
      queue-name: demo_queue
      concurrent-consumers: 1
      max-concurrent-consumers: 5