spring:
  rabbitmq:
    addresses: cloud_url:port
    virtual-host: cloud-host
rabbitmq:
  micro:
    prop:
      exchange: demo-ex
      routing-key: demo.route
      queue-name: demo_queue
      concurrent-consumers: 1
      max-concurrent-consumers: 5