spring:
  application:
    name: spring-boot-rabbitmq-micro
  rabbitmq:
    addresses: localhost:5672
    virtual-host: dev-host
  profiles:
    active:
    - annotation 
rabbitmq:
  micro:
    prop:
      exchange: demo-ex
      routing-key: demo.route
      queue-name: demo_queue
      concurrent-consumers: 1
      max-concurrent-consumers: 5