spring:
  datasource:
    url: jdbc:mysql://mysql-server:3306/poc?createDatabaseIfNotExist=True
    username: root
    password: root
    initialization-mode: always
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      format-sql: true
  batch:
    job:
      enabled: false
    initialize-schema: always  
      
      
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka
