spring:
  datasource:
    url: jdbc:mysql://ec2-13-235-103-124.ap-south-1.compute.amazonaws.com:3306/poc
    username: root
    password: root
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      format-sql: true  