spring:
  datasource:
    url: jdbc:mysql://localhost:3306/poc
    username: root
    password: root
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      format-sql: true
      
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761