spring:
  datasource:
    url: jdbc:mysql://mysql-service:3306/poc
    username: root
    password: root
    initialization-mode: always
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      format-sql: true
      
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-service:8761/eureka